export default defineAppConfig({
  pages: [
    'pages/events/index',
    'pages/login/index',
    'pages/events/detail',
    'pages/register/index',
    'pages/my/index',
    'pages/checkin/index',
    'pages/admin/index',
    'pages/podcast/index',
    'pages/podcast/player',
    'pages/points/mall',
    'pages/points/my',
    'pages/points/orders',
  ],
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#000000',
    navigationBarTitleText: 'DIG RUNNING CLUB',
    navigationBarTextStyle: 'white',
    backgroundColor: '#000000',
    backgroundColorTop: '#000000',
    backgroundColorBottom: '#000000',
    enablePullDownRefresh: false,
  },
})
